FAKE_LIST_USER = [
    {
        "id": 80,
        "password": "123",
        "last_login": None,
        "uuid": "U01",
        "firstName": "Sang",
        "lastName": "Nguy?n ",
        "username": "sang01",
        "mobile": "122949256",
        "email": "sanghh111@gmail.com",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 81,
        "password": "123",
        "last_login": None,
        "uuid": "U02",
        "firstName": "Anh",
        "lastName": "Nguy?n ",
        "username": "anh2103",
        "mobile": "038169735",
        "email": "vietanh01@gmail.com",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 82,
        "password": None,
        "last_login": None,
        "uuid": "U03",
        "firstName": "CH�U",
        "lastName": "PH?M",
        "username": "vietanh01",
        "mobile": "078644016",
        "email": "vietanh02@gmail.com",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 83,
        "password": None,
        "last_login": None,
        "uuid": "U04",
        "firstName": "Th?ng",
        "lastName": "Nguy?n ",
        "username": "vietanh02",
        "mobile": "091537249",
        "email": "vietanh03@gmail.com",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 84,
        "password": None,
        "last_login": None,
        "uuid": "U05",
        "firstName": "H�a",
        "lastName": "PH?M",
        "username": "vietanh03",
        "mobile": "010677834",
        "email": "vietanh01",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 85,
        "password": None,
        "last_login": None,
        "uuid": "U06",
        "firstName": "Minh",
        "lastName": "Nguy?n ",
        "username": "vietanh04",
        "mobile": "116579140",
        "email": "vietanh02",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 86,
        "password": None,
        "last_login": None,
        "uuid": "U07",
        "firstName": "Ph�",
        "lastName": "PH?M",
        "username": "vietanh05",
        "mobile": "120840085",
        "email": "vietanh03",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": True,
        "is_blocked": True
    },
    {
        "id": 87,
        "password": None,
        "last_login": None,
        "uuid": "U08",
        "firstName": "Th?ng",
        "lastName": "Nguy?n ",
        "username": "vietanh06",
        "mobile": "072676747",
        "email": "vietanh04",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 88,
        "password": None,
        "last_login": None,
        "uuid": "U09",
        "firstName": "H�a",
        "lastName": "PH?M",
        "username": "vietanh07",
        "mobile": "068824202",
        "email": "vietanh05",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": True,
        "is_blocked": True
    },
    {
        "id": 89,
        "password": None,
        "last_login": None,
        "uuid": "U10",
        "firstName": "Minh",
        "lastName": "Nguy?n ",
        "username": "vietanh08",
        "mobile": "041218770",
        "email": "vietanh06",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 90,
        "password": None,
        "last_login": None,
        "uuid": "U11",
        "firstName": "Ph�",
        "lastName": "PH?M",
        "username": "vietanh09",
        "mobile": "037838326",
        "email": "vietanh07",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": True,
        "is_blocked": True
    },
    {
        "id": 91,
        "password": None,
        "last_login": None,
        "uuid": "U12",
        "firstName": "Th?ng",
        "lastName": "Nguy?n ",
        "username": "vietanh10",
        "mobile": "129678368",
        "email": "vietanh08",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": True
    },
    {
        "id": 92,
        "password": None,
        "last_login": None,
        "uuid": "U13",
        "firstName": "H�a",
        "lastName": "PH?M",
        "username": "vietanh11",
        "mobile": "038754548",
        "email": "vietanh09",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": True
    },
    {
        "id": 93,
        "password": None,
        "last_login": None,
        "uuid": "U14",
        "firstName": "Minh",
        "lastName": "Nguy?n ",
        "username": "vietanh12",
        "mobile": "042549037",
        "email": "vietanh10",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": True,
        "is_blocked": False
    },
    {
        "id": 94,
        "password": None,
        "last_login": None,
        "uuid": "U15",
        "firstName": "Ph�",
        "lastName": "PH?M",
        "username": "vietanh13",
        "mobile": "068400927",
        "email": "vietanh11",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": True
    },
    {
        "id": 95,
        "password": None,
        "last_login": None,
        "uuid": "U16",
        "firstName": "Th?ng",
        "lastName": "Nguy?n ",
        "username": "vietanh14",
        "mobile": "104523205",
        "email": "vietanh12",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": True
    },
    {
        "id": 96,
        "password": None,
        "last_login": None,
        "uuid": "U17",
        "firstName": "H�a",
        "lastName": "PH?M",
        "username": "vietanh15",
        "mobile": "042826941",
        "email": "vietanh13",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": True,
        "is_blocked": False
    },
    {
        "id": 97,
        "password": None,
        "last_login": None,
        "uuid": "U18",
        "firstName": "Minh",
        "lastName": "Nguy?n ",
        "username": "vietanh16",
        "mobile": "042169352",
        "email": "vietanh14",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": False
    },
    {
        "id": 98,
        "password": None,
        "last_login": None,
        "uuid": "U19",
        "firstName": "Ph�",
        "lastName": "PH?M",
        "username": "vietanh17",
        "mobile": "049206933",
        "email": "vietanh15",
        "passwordHash": "123",
        "registeredAt": "2022-10-15T00:00:00Z",
        "intro": "",
        "profile": "",
        "is_active": True,
        "is_reported": False,
        "is_blocked": True
    }
]